oync:
    image: "selcolumbia/oync"
    links:
      - "db:db"
    environment:
        OYNC_OSM_API_URL: 'http://ibadan.gridmaps.org'
    command:  ./bin/run-oync.sh

db:
    image: "mdillon/postgis:9.4"
    environment:
        POSTGRES_DB: 'osm'
