oync:
    image: "selcolumbia/oync"
    volumes:
      - ./:/oync-src
    links:
      - "db:db"
    ports:
      - "3000:3000"
    environment:
        OYNC_OSM_API_URL: 'http://localhost:3000'
        OYNC_TEST_DATA_DIR: '/oync/test/data'
    command:  ./bin/run-oync-tests.sh

db:
    image: "mdillon/postgis:9.4"
    environment:
        POSTGRES_DB: 'osm'
