oync:
    image: "selcolumbia/oync"
    volumes:
      - ./:/oync-src
    links:
      - "db:db"
    environment:
        OYNC_OSM_API_URL: 'http://ibadan.gridmaps.org'
db:
    image: "mdillon/postgis:9.4"
    environment:
        POSTGRES_DB: 'osm'
